# -*- coding: utf-8 -*-
{
    'name': 'Optical ERP',
    'version': '13.1.3',
    'category': 'Point Of Sale',
    'author': 'D.Jane, Fauniq',
    'price': 70,
    'currency': 'EUR',
    'license': 'OPL-1',
    'support': 'https://alhaditech.com',
    'sequence': 1,
    'summary': 'Solution for Optical(EYE) shops and clinics',
    'description': "",
    'depends': ['base','sale','doctor','patient'],
    'data': [
          "security/ir.model.access.csv",
        "data/data.xml",
        "views/test_type.xml",
        "views/prescription.xml",
        'views/patient_inherit.xml',
        'views/doctor_inherit.xml',
        "views/view.xml",
    ],
    'images': ['static/description/background.png'],
    'qweb': ['static/src/xml/pos_stock.xml'],
    'installable': True,
    'application': True,
}
